title: "2020FS-UZH-600-009a-Schreibuebung"
description: "Materialien der Sitzung 11 (Review) der Veranstaltung UZH-600-009a-Schreibübung von Andrea Schweizer"
plugins:
  - jekyll-default-layout
  - jekyll-relative-links
  - jekyll-titles-from-headings
